INSERT INTO employees (name, phone, email, bio, skills, location, image, created_at) VALUES ('Tobias Tønnessen', '41692977', 'tobias.tonnessen@sonat.no', 'Tobias er seniorkonsulent i Sonat og er en veldig aktiv person som liker sport. Hans akademiske reise har ført ham til tre ulike land, med studieopphold i New Zealand, Australia og Spania, noe som har gitt ham en unik internasjonal erfaring. Han har en bachelorgrad som automasjonsingeniør og en mastergrad innen intelligente systemer. Tobias har en lidenskap for automatisering og optimalisering av prosesser, og betraktes som en entusiast på dette området.', 'Systemutvikling, App development, designutvikling', 'Oslo', 'https://cdn.sanity.io/images/pj4buh1l/production/d3435d06a5b2fcc87605fcd7b5b4f2e4db142628-1262x1684.png', '2025-03-06 17:59:43.376648+00');
INSERT INTO employees (name, phone, email, bio, skills, location, image, created_at) VALUES ('Bendik Bleikli', '40487018', 'bendik.bleikli@sonat.no', 'Bendik har erfaring med utvikling av VR-applikasjoner til læring/erfaringsbygging, forskning og rehabilitering. Hovedkompetansen ligger i C# og spillmotoren Unity.
Han har også erfaring som embeddedutvikler hvor han har fått prøve seg på driverutvikling, Qt-applikasjoner, samt testing og sertifisering av functional safety-programvare.
På fritiden liker han å drive med buldring, dataspill og musikk.', 'VR, systemutvikling og embedded software.', 'Bergen', 'https://cdn.sanity.io/images/pj4buh1l/production/7d687aca03e09254b83067faea7efc72ab915611-931x1600.jpg', '2025-03-06 17:59:43.376648+00');
INSERT INTO employees (name, phone, email, bio, skills, location, image, created_at) VALUES ('Arve Nygård', '97722513', 'arve.nygaard@sonat.no', 'Arve har en Master of Science fra NTNU med spesialisering innen kunstig intelligens. I prosjektene har han hatt ansvar for arkitektur og løsningsdesign, utvikling, utviklingsmiljø, leveranser og har hatt roller som arkitekt, utvikler og teamleder. Han har bred erfaring på både NET- og Java/Open Source-stacken og har prosjekterfaring med Azure, AWS og Google Cloud Platform.

Arve har erfaring med arkitektur for forretningskritiske systemer i bransjer som energi, transport, telecom og finans.', 'Analyse, arkitektur, prosjektplanlegging, utvikling.', 'Trondheim', 'https://cdn.sanity.io/images/pj4buh1l/production/ac7bd0f12fe01a44bb0f10e8d7d0b7e6fc8efb69-1070x1415.jpg', '2025-03-06 17:59:43.376648+00');
INSERT INTO employees (name, phone, email, bio, skills, location, image, created_at) VALUES ('Arnstein Flemmen', '99157351', 'arnstein@sonat.no', 'Arnstein Flemmen er en allsidig utvikler som har vært i Sonat siden 2013. Han har vært med på alt fra drift av kinoer, salgssystemer og selger nå pensjon og forsikringer. Høydepunktet var valuttatrading, etterhvert komplekse algoritmer kjørende på server i New York. Han tok opp kampen mot de beste og endte med gode erfaringer.. 

Ingenting er kjedelig og alt er spennende men elsker å bli utfordret. Etter 15 år med med utvikling er det Java som fortsatt er favoritten og han heller mot frontend. Ingen grunn til at systemene ikke skal se fine ut også! 

Fritiden blir brukt på et uendelig hav av hobbyer som jakt, fiske, ølbrygging og barna. Arnstein valgte Sonat grunnet fokuset på videre kompetansebygging og særdeles dyktige kollegaer.', 'UX design, teknisk arkitektur og java.', 'Bergen', 'https://cdn.sanity.io/images/pj4buh1l/production/b665e4a44f195c46d9eb934496c79c1a6a3653d1-2200x1467.jpg', '2025-03-06 17:59:43.376648+00');
INSERT INTO employees (name, phone, email, bio, skills, location, image, created_at) VALUES ('Arild Johan Takvam', '91736278', 'arild.takvam@sonat.no', 'Arild har jobbet i Sonat siden 2015 og i Oslo siden 2016. Han var med å starte avdelingen i Oslo, vikarierte et halvår som daglig leder og sitter i dag som valgt medlem i konsernstyret. Arild er har en mastergrad i informasjonsvitenskap og har jobbet som utvikler siden 2007. I senere år også fått god erfaring som Scrum Master, teamleder og tech lead. Dette er roller han trives veldig godt med, han har det aldri så bra som når han får bidra til at andre har det bra og leverer i jobben sin. Som utflyttet Bergenser tar Arild ansvar og henger opp Brann-flagget i tide og utide et drøyt bekkaspark fra Vålerengen sin stadion. Utover det trives han overraskende godt på Oslos østkant, er alenepappa til to halvparten av tiden, fotballtrener og liker å vikariere som lærer i Kodetimen på skolen. Arild valgte Sonat i 2015 fordi han ønsket en arbeidsplass der han ble utfordret faglig og sosialt, en arbeidsplass der han kunne utvikle seg og med folk han kunne strekke seg etter.', 'Teamleder, Scrum Master, systemutvikler', 'Oslo', 'https://cdn.sanity.io/images/pj4buh1l/production/c8dc203a874b80e4a45b195d7a3bb744fabcfea0-2048x1365.jpg', '2025-03-06 17:59:43.376648+00');
INSERT INTO employees (name, phone, email, bio, skills, location, image, created_at) VALUES ('Andreas Vikne', '97492646', 'andreas.vikne@sonat.no', 'Andreas har en master i programutvikling fra Universitet i Bergen/Høgskulen på Vestlandet. Han arbeider nå som seniorkonsulent hos Sonat i Bergen.
Han har flere års erfaring med systemutvikling fra offentlig sektor hvor han blant annet har vært en sentral bidragsyter i prestisjefylte prosjekter. Kjernekompetansen er design og utvikling av system- og web-api. Han jobber for at løsninger skal være robuste, sikre og enkle å vedlikeholde.
På fritiden liker Andreas å stå på ski, surfe og danse kubansk salsa.

Grunnen til at Andreas valgte Sonat var fordi selskapet fokuserer på faglig utvikling og har rykte på seg for å ha et svært godt arbeidsmiljø.', 'Systemutvikling, backend, Kotlin, Java', 'Bergen', 'https://cdn.sanity.io/images/pj4buh1l/production/1bdf7691690815b10c829f508ad262cf824c3e9b-394x484.jpg', '2025-03-06 17:59:43.376648+00');
INSERT INTO employees (name, phone, email, bio, skills, location, image, created_at) VALUES ('Andreas Garvik', '47174960', 'andreas.garvik@sonat.no', 'Andreas har en mastergrad i programvareutvikling ved HVL og UiB inkludert et utvekslingssemester ved QUT i Brisbane, Australia. Gjennom studietiden arbeidet han på deltid som juniorvikler og systemutvikler i ulike selskaper innenfor finans og opparbeidet seg mye erfaring på kort tid.

Andreas er interessert i alt av teknologi, elsker å lære og trives godt med nye utfordringer. På fritiden har Andreas en aktiv livsstil med styrketrening, racketsport og buldring. Ellers liker han å reise rundt i verden og har stor interesse for musikk og matlaging.

Andreas valgte Sonat på grunn av det sterke fagmiljøet og fokuset på både faglig og personlig utvikling, han ser på kombinasjonen som en perfekt plass å vokse videre.', 'Systemutvikling, frontend og backend.', 'Oslo', 'https://cdn.sanity.io/images/pj4buh1l/production/eaef9efa72421dab57a3c9388abe5fed3ce17fcb-3512x5401.jpg', '2025-03-06 17:59:43.376648+00');
INSERT INTO employees (name, phone, email, bio, skills, location, image, created_at) VALUES ('Jonny Klemetsen', '98219551', 'jonny.klemetsen@sonat.no', 'Jonny er grunder av Sonat gruppen og tilsatt som forretningsutvikler i Bergen. Jonny har over 10 års erfaring som konsernsjef i Sonat gruppen.

Han startet IT karrieren på gutterommet i 1980 da han fikk sin første datamaskin som var en TI 99/4A De første utviklingsprosjektene var spillutvikling på hjemmedatamaskinen. i 1984 gikk turen til NTNU hvor han tok en master i Marinteknikk.

Som forretningsutvikler har Jonny fokus på å utvikle Sonat gruppen på tvers av alle selskap. Han har et sterkt ønske om å skape verdi for Sonat sine kunder og ansatte. Han har god kompetanse på digitalisering. 

Jonny er også styreleder i forhelse.no som er Forskningssenter for digitale psykiske helsetjenester og har således gjennom 8 år bygget opp solid kunnskap om sektoren.

Fritiden brukes til å lade batteriene med musikk, fotball på TV eller trening der løping og vekttrening er hovedaktiviteten. 

Har en datter som også er teknologiinteressert og i IT bransjen.', 'Forretningsutvikler

Ledelse, digitalisering, forskning, innovasjon og helse.', 'Bergen', 'https://cdn.sanity.io/images/pj4buh1l/production/a3cf37d85471842fbaf95f89ff68d226aaf10136-1467x1462.jpg', '2025-03-06 17:59:43.376648+00');
INSERT INTO employees (name, phone, email, bio, skills, location, image, created_at) VALUES ('Thomas Mellin-Olsen', '91798489', 'thomas.mellin-olsen@sonat.no', 'Thomas har lang erfaring fra relasjonsbygging og salg av konsulenttjenester. Han er opptatt av at de rundt han lykkes med sine faglige ambisjoner og trives på jobb. 

Thomas er en engasjert pådriver og har hatt roller i organisasjonsarbeid næringslivet i Bergen, både næringslivet generelt og spesielt rettet mot Energi. Han var i sin ungdom en habil lengdehopper og jobber nå for at kollegaer og kunder skal kunne nå lenger, og oppnå gode resultater i sine prosjekter. 

Thomas er en aktiv familiefar med to jenter og engasjert friidrettstrener for dem. Han er opptatt av å skape gode og langvarige relasjoner med både kunder og kollegaer.', 'Salg og forretningsutvikling i Sonat.', 'Bergen', 'https://cdn.sanity.io/images/pj4buh1l/production/20a9bcf935d75ea8b3447c1562858d276989abeb-2200x1467.jpg', '2025-03-06 17:59:43.376648+00');
INSERT INTO employees (name, phone, email, bio, skills, location, image, created_at) VALUES ('Geir Lillebø', '92885110', 'geir.lilleboe@sonat.no', 'Geir er leder for forretningsutvikling og salg i Sonat. Han er svært opptatt av mennesker og hvorfor de agerer som de gjør i forskjellige situasjoner. 

Geir anser seg selv som et av tannhjulene som kreves for at Sonat skal ha fornøyde kunder og fornøyde konsulenter. Fremste IT-prestasjon er fremdeles adminscriptet han lagde til CS i 2004, heldigvis er de mellommenneskelige kvalitetene sterkere og han gjør det han kan for å være et godt medmenneske. 

På fritiden er det sunne hobbyer som fotball, MMA, poker og gaming som gjelder, dessverre foran skjermen mer enn i aktivitet. 

Geir valgte Sonat fordi han ville ha et spisset fagmiljø og et selskap med en størrelse og struktur som gjorde at alle hadde en stemme og en påvirkning.', 'Salg, forretningsutvikling og prosjektledelse.', 'Bergen', 'https://cdn.sanity.io/images/pj4buh1l/production/51249c7b5934faaaeccdd570326716e08be8159e-2200x1467.jpg', '2025-03-06 17:59:43.376648+00');
INSERT INTO employees (name, phone, email, bio, skills, location, image, created_at) VALUES ('Nadeem Qureshi', '45222604', 'nadeem@sonat.no', 'Nadeem er daglig leder, rådgiver, gründer og entusiast. Han er veldig nysgjerrig på teknologi og lar seg lett begeistre av digital nyskapning. Han utvikler kontinuerlig sin kompetanse innen områder som krever forretningsforståelse. Her kan vi nevne områder som; arkitektur, prosjektdesign, systemutvikling og endringsledelse. Fra sin tid som gründer har han beholdt hjertet for likesinnede. Han går derfor aldri glipp av en anledning til å skape møteplasser eller bidra til at andre ildsjeler skal lykkes.', 'Daglig leder

Forretningsutvikling, innovasjon, arkitektur, prosjektdesign, systemutvikling og endringsledelse', 'Trondheim', 'https://cdn.sanity.io/images/pj4buh1l/production/39374b91830ce7d6daeb2385f1487edb97f40eba-2123x2829.jpg', '2025-03-06 17:59:43.376648+00');
INSERT INTO employees (name, phone, email, bio, skills, location, image, created_at) VALUES ('Tobias Laupsa Nilsen', '40631865', 'tobias.nilsen@sonat.no', 'Tobias har en mastergrad i biologisk inspirert kunstig intelligens fra NTNU, men bruker den sjelden. Istedenfor å lage robothjerner har han jobbet som utvikler på en lang rekke web-prosjekter innen telekom, media og spesielt bank og finans. 

Tobias liker å løse problemer og er kanskje den eneste i norge som liker å fikse andres (og egne) bugs. Når han ikke er på jobb plager han sin samboer og barn med ting de ikke er veldig interesserte i, gamer og forsøker å løpe fortere og løfte tyngre. T

obias byttet jobb fra et stort internasjonalt konsulentselskap til Sonat fordi han liker fleksibilitet, flinke folk og flate hierarkier.', 'Systemutvikling, web, .net, java og mobil', 'Bergen', 'https://cdn.sanity.io/images/pj4buh1l/production/9661cc96e9008d0a491a22d38c550d29663d81af-1467x1711.jpg', '2025-03-06 17:59:43.376648+00');
INSERT INTO employees (name, phone, email, bio, skills, location, image, created_at) VALUES ('Yngve Villanger', '91132887', 'yngve.villanger@sonat.no', 'Yngve har bakgrunn som forsker på algoritmer, men har de siste ti årene hovedsakelig jobbet med analyse av sensordata. Eksempler på dette inkluderer separasjon og lokalisering av lydkilder i akustiske data, ML-modeller for klassifisering av last og feiltilstander for pumper, og avviksdeteksjon. Han mener at analyseresultater har høyere verdi hvis man kjenner begrensningene i de brukte metodene, kvaliteten på inndata og verifiserer estimerte verdier mot uavhengige målinger. Den beste løsningen er den enkleste og reneste som er i stand til å løse problemet på en tilfredsstillende måte. De siste to årene har han hatt ansvar for å utvikle et Azure-basert tilstandsovervåkingssystem for roterende maskiner for det maritime segmentet. Dette har gitt Yngve erfaring med å lede driften av skybaserte løsninger, containerbaserte løsninger og kontinuerlig integrering og utgivelse av nye løsninger. 
I flere år jobbet han som forsker på algoritmer ved Universitetet i Bergen. Hovedfokuset i forskningsarbeidet var å beskrive teknikker som utnytter strukturer i inndataene for å forbedre kjøretiden.', 'Utvikling, arkitektur og analyse. ', 'Bergen', 'https://cdn.sanity.io/images/pj4buh1l/production/12ec5f440eddb1ec085cc564173395ab2c851e87-3024x4032.jpg', '2025-03-06 17:59:43.376648+00');
INSERT INTO employees (name, phone, email, bio, skills, location, image, created_at) VALUES ('Malik Aasen', '90560239', 'malik.aasen@sonat.no', 'Malik er konsulent i Sonat Bergen.Han har en mastergrad i programutvikling fra Høgskulen på Vestlandet & UiB med spesialisering innen maskinlæring. Malik har erfaring med maskinlæring, backend, frontend og er glad i nye utfordringer.På fritiden går det mest i styrketrening, gaming og katt, samt en interesse for bygging av tastatur.', 'Backend, maskinlæring og frontend basert på React', 'Bergen', 'https://cdn.sanity.io/images/pj4buh1l/production/e017756c0fc269e99186f0ffb9f6fb04e2590b30-2686x1756.jpg', '2025-03-06 17:59:43.376648+00');
INSERT INTO employees (name, phone, email, bio, skills, location, image, created_at) VALUES ('Joakim Nygård', '45492420', 'joakim.nygard@sonat.no', 'Joakim er senior systemutvikler, techlead og teamleder. Han sørger for at teknologiske løsninger vil fungere i tråd med forretningsmålene og skaper langsiktig verdi for kundene. Joakim har mange års erfaring som full-stackutvikler med Microsoft-teknologier, ulike frontend-rammeverk og Microsoft Azure skyplattform.

Joakim har erfaring med virksomhetskritiske systemer fra bransjer som helse, bank/finans, pensjon, eiendomsmegling', 'Analyse, forretningsstrategi, arkitektur, systemutvikling, sikkerhet', 'Trondheim', 'https://cdn.sanity.io/images/pj4buh1l/production/4b652a002a4c5b28a43e62492b592955fc2fb3d6-6923x4618.jpg', '2025-03-06 17:59:43.376648+00');
INSERT INTO employees (name, phone, email, bio, skills, location, image, created_at) VALUES ('Haakon Skramstad ', '40890819', 'Haakon.skramstad@sonat.no', 'Haakon Skramstad er daglig leder. Haakon har lang erfaring fra salg i konsulentvirksomheter og kommer fra stillingen som salgssjef for Professional services i CapGemini. ', 'Direktør for forretningsutvikling, salg og rekruttering.', 'Oslo', 'https://cdn.sanity.io/images/pj4buh1l/production/fab628fce475ec4844b8ad622f9879a438dd9a2e-2022x1438.png', '2025-03-06 17:59:43.376648+00');
INSERT INTO employees (name, phone, email, bio, skills, location, image, created_at) VALUES ('Christian Whyatt Holvik', '47675230', 'christian.holvik@sonat.no', 'Christian har erfaring som Java utvikler innen finans, hvor han fikk bryne seg på alt fra webrequests, til camel til database. Det gøyeste i arbeidsdagen hans er å lære seg ny teknologi og nye rammeverk.

Han har jobbet med svære systemer med flere interne og eksterne integrasjoner, og
monitoring av disse. Christian liker også å se arkitekturen av det han jobber på, for å kunne holde en rød tråd mens man utforsker og videreutvikler produktet.

På fritiden holder Christian på med gaming,serier, dykking, trening og noe musikk.
Christian valgte Sonat på grunn av utviklingsmulighetene, og fordi han ble imponert over kunnskapen til bekjentskapene fra Sonat.', 'Systemutvikling Java og ulike rammeverk innen backend. ', 'Bergen', 'https://cdn.sanity.io/images/pj4buh1l/production/f24cca3743b4b35c6a7030e0138a98f8b727db99-3512x6240.jpg', '2025-03-06 17:59:43.376648+00');
INSERT INTO employees (name, phone, email, bio, skills, location, image, created_at) VALUES ('Bendik Mathias Johansen', '98686957', 'bendik.johansen@sonat.no', 'Bendik er en engasjert fullstack-utvikler som tidligere har jobbet i bank. Han liker godt systemutvikling og backend, men han er også dyktig på frontend.

Bendik er utdannet dataingeniør fra Høgskulen på Vestlandet, og tok master i programutvikling på normert tid ved siden av fulltidsjobb. På fritiden liker han blant annet å skrive kode, spille gitar og lese bøker.

Bendik begynte i Sonat i 2021. Han utsøkte Sonat fordi det virker som et veldig godt miljø som han vil trives i, både faglig og sosialt.', 'Systemutvikling, C#, JavaScript/TypeScript, React, .NET Core', 'Bergen', 'https://cdn.sanity.io/images/pj4buh1l/production/7a5345dd3c3fd3eb5ce346463ab6d5d9a87e62b4-2788x1756.jpg', '2025-03-06 17:59:43.376648+00');
INSERT INTO employees (name, phone, email, bio, skills, location, image, created_at) VALUES ('Øyvind Øyen', '99525150', 'oyvind.oyen@sonat.no', 'Øyvind Øyen er fullstack utvikler med lang erfaring innen .NET og React på både store og små prosjekter. 

Han har stort fokus på god arkitektur, kode-kvalitet og lesbarhet for å sikre at koden kan vedlikeholdes av kunden selv. "Pen kode er god kode". Han er også en big believer i det å dele kunskap ute hos kunden. 

På fritiden finner vi Øyvind på løpetur eller syngende i kor når han ikke er hjemme med sin kone, to barn, en katt og fem høner.', 'Design og systemutvikling basert på javascript,.net, C# og MS-SQL Server.', 'Bergen', 'https://cdn.sanity.io/images/pj4buh1l/production/d6c513a327dfea8a4592214c2119594003743154-2200x1467.jpg', '2025-03-06 17:59:43.376648+00');
INSERT INTO employees (name, phone, email, bio, skills, location, image, created_at) VALUES ('Ørjan Bergmann', '47349050', 'orjan.bergmann@sonat.no', 'Ørjan Bergmann er partner og seniorkonsulent i Sonat. 

Han har en doktorgrad i informatikk og har jobbet mange år som forsker innen bildebehandling av psykose og multippel sklerose. Som konsulent har han jobbed både som prosjektleder, team lead og backend utvikler. 

På fritiden forsøker han å trene til maraton, i tillegg til å være pappe for to døtre. Begge deler er like slitsomt! 

Barna mener han er god til å lage taco og enda bedre til å sitte foran datamaskinen. Drømmen, når barna er blitt store, er å flytte tilbake til USA der han tidligere har studert og jobbet i flere år. 

Ørjan valgte Sonat fordi han ville jobbe sammen med flinke mennesker, og den nyeste teknologiene.', 'Bildebehandling, optimering og maskinlæring.', 'Bergen', 'https://cdn.sanity.io/images/pj4buh1l/production/e8445b911d725fcc38e0a01da02bea2b46f6b4cf-2200x1467.jpg', '2025-03-06 17:59:43.376648+00');
INSERT INTO employees (name, phone, email, bio, skills, location, image, created_at) VALUES ('Tore Løvmo', '90890710', 'tore.lovmo@sonat.no', 'Tore Løvmo liker de tunge utfordringene i koden men setter stor pris på å løfte blikket for å se den helhetlige tankegangen rundt løsningene. 

Han har jobbet i flere ulike oppdrag med software- og produktutvikling, teknisk prosjektledelse, arkitektur, continuous deployment og digitalisering. Som utvikler har han jobbet primært med Java-rammeverk og er en fremragende utvikler i både Java og teknologiene rundt. Bred kompetanse på backend og integrasjon. 

Tore har også kompetanse på en rekke andre teknologier, herunder moderne metodeverk, andre utviklingsrammeverk, skyløsninger og front-end løsninger. 14 års erfaring hovedsakelig innen bank, forsikring/pensjon. 

På fritiden er han er opptatt av å bidra til at barn har et tilbud på de ulike arenaene som hans barn har deltatt i. Dette har gitt han ulike verv fra foreldrekontakt til styremedlem og er nå trener i håndball for minstemann. 

Valget falt på Sonat grunnet fokusen som ligger på faglig utvikling både felles og individuelt, det hjalp at han allerede hadde flere kompiser her. :-)', 'Software- og produktutvikling, teknisk prosjektledelse, arkitektur, continuous deployment og digitalisering', 'Bergen', 'https://cdn.sanity.io/images/pj4buh1l/production/d4cfb3475757c58b0c4325cf510835617adcdae1-2000x1363.jpg', '2025-03-06 17:59:43.376648+00');
INSERT INTO employees (name, phone, email, bio, skills, location, image, created_at) VALUES ('Thomas Nøkling', '90273736', 'thomas.nokling@sonat.no', 'Thomas er ikke så høy, men det er heldigvis både hans kunnskap og takhøyde. Han har bred erfaring som konsulent, fra bransjer som bank og finans, tele- og kommunikasjon, kringkasting og offentlig sektor. Ekspertisen hans er Java backend, men han har også erfaring som arkitekt, fullstackutvikler og database. 

Utenom jobben, så har Thomas kone, 2 barn og hund. På fritiden liker han ølbrygging, programmere mikrokontrollere, bygge lego, dykke, klatre og produsere musikk. 

Det Thomas synes er best med å være konsulent, er problemløsing. Det å kunne ta fatt på en problemstilling, og komme frem til en god løsning - Er en ganske ubeskrivelig følelse. Hans kone er ikke nødvendigvis enig i at alle problemer trenger å løses. Noen ganger er det best å bare lytte.', 'Design og systemutvikling med Java, samt ulike rammeverk for Front-og Backend-utvikling.', 'Bergen', 'https://cdn.sanity.io/images/pj4buh1l/production/19548efb562092dae306d65c4f54215b4db7566a-2200x1467.jpg', '2025-03-06 17:59:43.376648+00');
INSERT INTO employees (name, phone, email, bio, skills, location, image, created_at) VALUES ('Stig Hausberg', '91685476', 'stig.hausberg@sonat.no', 'Stig Hausberg er partner og har vært med i Sonat siden oppstarten i 2012. 

Stig er en allsidig fullstack utvikler som har jobbet i både Microsoft og Java verden i forskjellige oppdrag. Stig tar raskt eierskap til prosesser i nye oppdrag og har bred erfaring innen skyløsninger, og har fått solid erfaring med sikkerhet og API de siste årene. Han har god domeneinnsikt innen finans, fra forsikring, verdipapir til Bank. Han har bachelor fra Norge og Master fra Australia. 

Når ikke Stig er på jobb, er han en fullstack familiemann, med stor kjærlihet for Ulriken og Bergensfjellene.', 'Systemutvikling med Microsoft .net og Java.', 'Bergen', 'https://cdn.sanity.io/images/pj4buh1l/production/2714eac14dfd814e50f17d1233cf399e32a29688-2200x1467.jpg', '2025-03-06 17:59:43.376648+00');
INSERT INTO employees (name, phone, email, bio, skills, location, image, created_at) VALUES ('Stian Almås', '90728801', 'stian.almaas@sonat.no', 'Stian Almås er en glad trønder som har vært i Sonat siden 2013 og har rundet to tiår (snart) som betalt utvikler. 

Han er utdannet sivilingeniør fra NTNU, men IT-interessen startet med Commodore 64 allerede på 80-tallet. Nå brukes interessen som full-stack utvikler i Sonat og til å holde seg oppdatert på ny teknologi. Han har jobbet mye innen bank og finans og har bransjekunnskap om emner som valutahandel, aksjesparekonto, skadeforsikring og SWIFTNet. Viktigere er likevel evnen til å sette seg inn i nye problemstillinger, ryddighet og evne til å levere løsninger. 

Fritiden går med til å være støtteapparat for to kommende fotball-storheter, eventuelt eSport-storheter. Sammen med sin kone har han også pådratt seg en dyr og tidkrevende uvane med å løpe storby-marathon i utlandet. 

Da Stian først valgte Sonat var det fordi det var et selskap fylt med de dyktigste folkene han visste om. Det er det fremdeles.', 'Systemutvikling, arkitektur, spesielt java og web-applikasjoner', 'Bergen', 'https://cdn.sanity.io/images/pj4buh1l/production/a727ed332c198c50920f5dc9bf0d9be819ce958b-2200x1467.jpg', '2025-03-06 17:59:43.376648+00');
INSERT INTO employees (name, phone, email, bio, skills, location, image, created_at) VALUES ('Stefan Bruvik', '45867666', 'stefan.bruvik@sonat.no', 'Stefan er en fullstack-utvikler med erfaring i både frontend- og backend-utvikling. Han har jobbet med en rekke teknologier og programmeringsspråk, inkludert React, Next.js, Svelte for frontend, og Java, Kotlin, C# samt .NET for backend. Stefan har også erfaring med utvikling på skyplattformer som Azure og AWS.
Hans tilnærming til arbeidet er preget av en metodisk utførelse og et øye for detaljer, noe som bidrar til å sikre kvaliteten på de løsningene han utvikler. Stefan arbeider effektivt både selvstendig og som en del av et team, og hans allsidighet gjør ham til en fleksibel ressurs i utviklingsprosjekter.
I tillegg til teknisk kompetanse, legger Stefan vekt på å forstå og møte kundenes behov, samtidig som han bidrar til en positiv brukeropplevelse gjennom de løsningene han er involvert i å utvikle. Hans evne til å håndtere varierte oppgaver innen fullstack-utvikling gjør ham til en verdifull del av ethvert utviklingsteam.', 'Fullstack', 'Bergen', 'https://cdn.sanity.io/images/pj4buh1l/production/cde3edf56ae6135e4290fdc5d90fe85fe75ee7f0-898x1500.jpg', '2025-03-06 17:59:43.376648+00');
INSERT INTO employees (name, phone, email, bio, skills, location, image, created_at) VALUES ('Sondre Johannessen', '94840795', 'sondre.johannessen@sonat.no', 'Sondre har erfaring med utvikling av IT systemer for mediebransjen. Han har jobbet med back-end og front-end løsninger, fra brukerportaler til videoredigering i skyen. Han har også jobbet som Tech Team Lead.', 'Utvikling, arkitektur, skytjenester', 'Bergen', 'https://cdn.sanity.io/images/pj4buh1l/production/84308157716a856eaabf74be2a31e5467b02eff5-1600x2610.jpg', '2025-03-06 17:59:43.376648+00');
INSERT INTO employees (name, phone, email, bio, skills, location, image, created_at) VALUES ('Sondre Eikanger Kvalø', '48190609', 'sondre@sonat.no', 'For Sondre har utvikling vært en del av livet helt siden han skrev sitt første "hello world" program på en Commodore 64 som tiåring. 

Han har bred erfaring å ha deltatt i utviklingsprosjekter innen mange ulike bransjer som offentlig sektor, bank, finans, forsikring og telekom. Det aller kjekkeste er likevel å bidra til åpen kildekode prosjekter noe han ha vært en talsmann for i mange sammenhenger også ute hos kundene sine. Fra sin oppvekst i bygdebyen Knarvik litt nord for Bergen trengte han ikke flytte så langt før han slo seg ned innen for Bergens kommunegrenser. Utdanningen ble gjennomført ved Universitet i Bergen der han gikk ut med hovedfag i Informasjonsvitenskap.

På fritiden er han gift og pappa til tre tenåringsjenter og har det med å rote seg bort i verv i diverse lokale organisasjoner. Til å ha startet karrieren med såpass høy skåre på nerdefaktoren har han etterhvert også funnet ut at han faktisk også liker å jobbe sammen med andre mennesker. 

Sondre elsker konsulentlivet fordi det gir en unik mulighet til både å bygge egen kompetanse både innenfor utviklingsfaget og i ulike miljøer og bransjer.', 'Systemutvikling, arkitektur, integrasjon, Java og .net', 'Bergen', 'https://cdn.sanity.io/images/pj4buh1l/production/033ac3bdad052365fbe766378606aab7067bc6d8-2200x1467.jpg', '2025-03-06 17:59:43.376648+00');
INSERT INTO employees (name, phone, email, bio, skills, location, image, created_at) VALUES ('Rune Meier', '93480414', 'rune.meier@sonat.no', 'Rune er en smidig rådgiver, en naturlig leder, med bred erfaring fra næringslivet, Forsvaret og politikken. Han er en sterk relasjonsbygger og skaper gode resultater gjennom samarbeid med eiere, god markedsforståelse og et sterkt tillitsforhold til ansatte. Rune er ivrig, leken og ikke redd for å ta på seg nye utfordringer.
Rune brenner for smidige løsninger, han er en dyktig coach og teknologisk rådgiver med et godt øye for menneskene og de strategiske foretningsmessige hensynene man må ta med for å skape gode resultater. Han har jobbet mye med veiledning av utviklingsteam, scrummastere og produkteiere og har bred erfaring med de ulike rollene i agile team. Hans driver er å identifisere og løse det som gir kunden størst mulig verdi. Han formidler, forankrer og kommuniserer godt internt og/eller eksternt, på norsk og engelsk.', 'Forretningsutvikling, Agile Coaching, Organisasjonsutvikling, Produktstrategi, Innsiktsarbeid/Data, Prosessforbedring, Teknologistrategi, Lean Software Development, Lean Startup, Prosjektledelse, Agile metoder, Lean Product Playbook, Målstyring – OKR
Workshops, Fasilitering, Foredrag', 'Oslo', 'https://cdn.sanity.io/images/pj4buh1l/production/7faef95c4b4fc4fdbba42cb505866d7c3cece497-1560x1195.png', '2025-03-06 17:59:43.376648+00');
INSERT INTO employees (name, phone, email, bio, skills, location, image, created_at) VALUES ('Ruben Havre', '97177154', 'ruben.havre@sonat.no', 'Ruben Havre er konsulent i Sonat, med fokus på web og mobil-utvikling. Han begynte allerede i løpet av ungdomsskolen å interessere seg for programmering, og hva man kan få til med en datamaskin. 

Ruben har mastergrad i programutvikling, og har 9 års erfaring med utvikling til både backend, frontend og mobil. Han begynte å jobbe med mobilutvikling på skolen i 2010, når Android fortsatt var relativt nytt, og han liker å automatisere oppgaver som kan spare en for tid, slik som bygging og utrulling av systemer. 

Ruben er bosatt ute i havgapet vest for Bergen, med samboer og to barn. På fritiden liker han å gå fjellturer, fotografere, spille fotball eller trene. 

Ruben valgte Sonat fordi han likte fokuset Sonat har på faglig utvikling, samt muligheten for å påvirke egen hverdag.', 'Systemutvikling, App, Frontend, backend, Java, Kotlin, Javascript', 'Bergen', 'https://cdn.sanity.io/images/pj4buh1l/production/47bfa3919a129a7c4859792e055027a765d27525-2200x1467.jpg', '2025-03-06 17:59:43.376648+00');
INSERT INTO employees (name, phone, email, bio, skills, location, image, created_at) VALUES ('Roy Kjellid', '98400800', 'roy.kjellid@sonat.no', 'Roy begynte i Sonat i 2013 og har lang erfaring med design, systemutvikling og arkitektur fra media, bank, og offentligsektor. 

Han er en allsidig ressurs som fungere både som utvikler,teknisk leder og arkitekt. Roy digger å lære nye teknologier, språk og metoder. Dette kommer frem når en ser alt det ulike han har jobbet med. 

I tillegg er han en svært utadvendt konsulent som bidrar mye for å skape en hyggelig arbeidsplass. 

På fritiden liker Roy seg på en topptur på ski, og hvis han får litt fritid fra familien så er det fullt mulig han titter på en fotballkamp med noe godt å drikke i hånden :)', 'Systemutvikling, teknisk arkitektur, java, .net og mobile løsninger.', 'Bergen', 'https://cdn.sanity.io/images/pj4buh1l/production/0e43fc153bbc26506dc5608b2b13b2332915bcc8-1467x1561.jpg', '2025-03-06 17:59:43.376648+00');
INSERT INTO employees (name, phone, email, bio, skills, location, image, created_at) VALUES ('Ricki Sickenger', '91344457', 'ricki.sickenger@sonat.no', 'Ricki er en dreven utvikler som har vært innom alt fra spillutvikling og AR/VR, til forsikring, shipping, og mediabransjen. Han trives både på backend og frontend. Ricki er stort sett å finne i rollen som systemutvikler, men har også erfaring med arkitekturplanlegging og prosjektledelse. 

Ricki begynte å programmere på Commodore 64 på 80-tallet, og jobbet i 10 år som spillutvikler etter endt utdanning. Det resulterte i Darkfall Online, en MMO som kom ut i 2009. Nå dyrker han spill-lidenskapen ved å lage spill på fritiden. Ellers bruker han fritiden på fjellturer, kajakk, vektløfting, og familien som består av kone, 3 barn og hund. 

Ricki har vært med i Sonat siden begynnelsen, og valgte Sonat for å være med å utvikle et selskap han og andre kunne trives i.', 'Systemutvikling, spillutvikling og frontend. Java, c#, Unity3D, Javscript, React, Golang m.fl.', 'Bergen', 'https://cdn.sanity.io/images/pj4buh1l/production/7d60e1f4ca5c838fef54f6e2121a15bbcbb3ab55-1467x1547.jpg', '2025-03-06 17:59:43.376648+00');
INSERT INTO employees (name, phone, email, bio, skills, location, image, created_at) VALUES ('Pétur Björn Thorsteinsson', '45869893', 'petur@sonat.no', 'Petur Björn har vært i Sonat siden 2016. Han kommer fra Island og flyttet til Norge i 2010. 

Petur har lang og variert erfaring innen IT og har jobbet med mange forskjellige teknologier og oppgaver. Han har både jobbet med å drifte IT systemer og å utvikle systemer,og har de siste årene jobbet mye innen devops og utvikling i AWS. 

På fritiden liker han å gå turer med familien, fluefiske, snowboard, trene fotball, matlagning og å lære om nye ting. 

Petur valgte Sonat fordi at de har et meget bra miljø - i Sonat får man veldig gode muligheter for å utvikle seg selv, i tillegg til flere spennende oppdrag.', 'Design og systemutvikling basert på Java/Opensource teknologi og Javascript for front-end utvikling samt bygg og deployment.', 'Bergen', 'https://cdn.sanity.io/images/pj4buh1l/production/20c91e7075e30b487e9dfcdfbde7761f649bf0f8-2200x1467.jpg', '2025-03-06 17:59:43.376648+00');
INSERT INTO employees (name, phone, email, bio, skills, location, image, created_at) VALUES ('Pål Trefall', '93479784', 'pal.trefall@sonat.no', 'Pål Trefall er en erfaren spillutvikler med fokus på det som skjer under panseret. 

Pål har jobbet mye med IoT-hub og digital tvilling med sanntids synkronisering. Han har også jobbet med kunstig inteligens, arkitektur, optimalisering og multi threading. 

Han har stor tro på selvkommenterende kode og kontinuerlig refaktorering."Dagen er ikke den samme hvis man ikke har slettet litt kode". Ledige stunder brukes helst til spillutvikling. 

Han får ut frustrasjon gjennom grappling, men bruker mest tid på sine to barn, kone, og to katter.', 'Systemutvikling og spillutvikling. C++, C# og Unity3D.', 'Bergen', 'https://cdn.sanity.io/images/pj4buh1l/production/61f015343c37239aefaaf8bc0d4adfe12f6a89f7-2200x1467.jpg', '2025-03-06 17:59:43.376648+00');
INSERT INTO employees (name, phone, email, bio, skills, location, image, created_at) VALUES ('Pål Skønberg Løvik', '‭47613989‬', 'pal.lovik@sonat.no', 'NULL', 'NULL', 'Trondheim', 'https://cdn.sanity.io/images/pj4buh1l/production/3b841b423dd5041ac80f3650bce064bfa4bc84bc-6988x4661.jpg', '2025-03-06 17:59:43.376648+00');
INSERT INTO employees (name, phone, email, bio, skills, location, image, created_at) VALUES ('Ole Røste Rabanal', '95087187', 'ole.rabanal@sonat.no', 'Ole har roller som rådgiver, løsningsarkitekt, og systemutvikler. Hans kompetanse og innsikt gjør ham til en verdifull partner for organisasjoner som ønsker å utnytte teknologi for å oppnå strategiske mål. Ole har erfaring på både NET- og Java/Open Source-stacken og har prosjekterfaring med ulike sky-platformer.

Ole har erfaring med virksomhetskritiske systemer fra bransjer som offentlig sektor, transport, oppdrett og produksjonsindustri.', 'Analyse, arkitektur, systemutvikling, IoT, forretningsutvikling.', 'Trondheim', 'https://cdn.sanity.io/images/pj4buh1l/production/ca661419799b5157f8a0aa9c93772ebe78ad7f52-6627x4420.jpg', '2025-03-06 17:59:43.376648+00');
INSERT INTO employees (name, phone, email, bio, skills, location, image, created_at) VALUES ('Olav Hugaas', '91571457', 'olav.hugaas@sonat.no', 'Olav har spisskompetanse på prosessforbedring, fasilitering, systemutvikling og systemintegrasjon. Han har lang erfaring med utviklingsverktøy som Javascript, Java, C#, MS SQL Server og Oracle. Olav har erfaring fra fasilitering av grupper ifm fusjonsprosesser og redesign av arbeidsprosesser. 

Han har utviklet løsninger for håndtering av medlemsregister, nettbank, Skipsadministrative system, pasientregister. Gjennom sin karriere har han bygget opp god bransjeinnsikt i bank, olje&energi, shipping og helse.', 'Prosessforbedring, fasilitering og systemutvikling innen Javascript, Java, C#, MS SQL Server og Oracle.', 'Bergen', 'https://cdn.sanity.io/images/pj4buh1l/production/00e743ee270579cbea86f0af08f53d5315976dc6-1467x1609.jpg', '2025-03-06 17:59:43.376648+00');
INSERT INTO employees (name, phone, email, bio, skills, location, image, created_at) VALUES ('Olav Alexander Mjelde', '98425342', 'olav.alexander.mjelde@sonat.no', 'Olav er partner og seniorkonsulent hos Sonat Consulting. 

Han har lang fartstid som fullstack-utvikler og systemforvalter, først i offentlig sektor og deretter innen bank og finans gjennom Sonat. Han har utviklet webbaserte gebyrkalkulatorer, portalløsninger, integrasjoner, mikrotjenester, chatbots og GDPR-implementeringer. 

Olav har jobbet mye med utvikling i backend, frontend, scoringsmotorer, databaser, responsivt design og semantisk web. 

Han Informasjonsbehandling ved NTNU og systemutvikling ved Noroff. På fritiden liker Olav å sykle på utforsykkel eller stisykkel, kjøre go-kart, drag race med Teslaen, fikse på hus og hjem eller finne på ting med samboer og barn. 

Olav er veldig glad i hardware og gaming, mikrokontrollere og overklokking datamaskiner. 

Olav liker det faglige, sosiale og innovative miljøet han har hatt i Sonat siden 2017.', 'Front- og backend-utvikling, relasjonsdatabaser, Android applikasjonsutvikling.', 'Bergen', 'https://cdn.sanity.io/images/pj4buh1l/production/5538799ac57154fbb07d701f8f9ce9e2582daba6-1467x1592.jpg', '2025-03-06 17:59:43.376648+00');
INSERT INTO employees (name, phone, email, bio, skills, location, image, created_at) VALUES ('Njål Nordmark', '94137784', 'Njaal.nordmark@sonat.no', 'Njål Nordmark er ein allsidig utvikler og arkitekt med ein forkjærlighet for skyteknologi. 

Han har jobba med alt frå live databasesynkronisering til micro-frontend og er klar for å testa nye ting når det passar til oppgåva som skal løysast. 

Frå utdanninga si som sivilingeniør i datateknikk har han tatt med seg ein spørrande og analytisk arbeidsmetodikk. Opp gjennom åra har han vore innom mange forskjellige sektorar som akademia, helse og media, men har dei siste åra jobba innan finans, både på bedrifts- og privatmarkedssida. 

Njål valgte å jobba for Sonat grunna det gode faglege og sosiale miljøet, samt at det er ein veldig friksjonsfri arbeidsplass.', 'Systemutvikling i Java, Spring, Hibernate, SQL, JavaScript. Utvikling til WordPress. Arkitektur, integrasjon.', 'Bergen', 'https://cdn.sanity.io/images/pj4buh1l/production/eb640d3c20b0e83a616468ff530a34147e0c8c93-2200x1467.jpg', '2025-03-06 17:59:43.376648+00');
INSERT INTO employees (name, phone, email, bio, skills, location, image, created_at) VALUES ('Nicholas Mowatt', '91136842', 'nicholas.mowatt@sonat.no', 'Med erfaring fra både utvikling, forretningsutvikling og teknologiledelse er Nicholas en allsidig ressurs. Han er spesielt interessert i å lære seg ny teknologi, noe som gir god faglig bredde. Sammen med kunde leder dette til verdifulle løsninger for både forretning og sluttbruker.

Nicholas har jobbet med det meste fra fullstack webutvikling via infrastruktur og meldingssystemer til data pipelines og maskinlæring. Han trives best sammen med folk som brenner for faget sitt og mener det er viktig å gi folk spillerom. De er som regel flinkere enn man tror.

Som småbarnsfar til to jenter går fritiden stort sett til familien. Utover det er teknologi interessen stor og det knotes for eksempel med nye programmeringsspråk eller Web3. Trening står også høyt på listen og han bruker gjerne ledig tid til å svømme, sykle eller løpe.

Nicholas valgte Sonat grunnet rykter om det beste faglige miljøet i byen.', 'Data Engineering, Arkitektur, Produktutvikling, Maskinlæring, Python', 'Bergen', 'https://cdn.sanity.io/images/pj4buh1l/production/7916896ce40e184b404e29de065ff3299b9ba101-884x1126.jpg', '2025-03-06 17:59:43.376648+00');
INSERT INTO employees (name, phone, email, bio, skills, location, image, created_at) VALUES ('Morten Kjetland', '45664979', 'morten.kjetland@sonat.no', 'Morten har sterk kompetanse innen arkitektur, systemutvikling og prosessautomatisering. Han er spesialist innen Scala, Java og Open-source og har erfaring fra bransjer som telecom, forsikring og media. 

Morten trives med nye problemstillinger og liker å dele kunskap.', 'Systemutvikling, teknisk arkitektur, Scala/Java', 'Bergen', 'https://cdn.sanity.io/images/pj4buh1l/production/8d42fe37a177dd772e77a68284b385901556f9ee-1467x1468.jpg', '2025-03-06 17:59:43.376648+00');
INSERT INTO employees (name, phone, email, bio, skills, location, image, created_at) VALUES ('Mikkel Espolin Birkeland', '91609149', 'mikkel.birkeland@sonat.no', 'Mikkel er en allsidig utvikler som brenner for gode og kreative løsninger på tekniske problemer. Han har stort sett holdt seg innenfor .NET verden i den profesjonelle delen av sin karriere som utvikler, men skrur gladelig på alle delene av tech-stacken. Mikkel synes det er vanskelig å finne en favoritt blant frontend, backend, DevOps og Cloud. Alt er så moro!

Mikkel har alltid jobbet som konsulent og gjennom denne perioden har det stort sett bare vært oppdrag innen olje- og gassbransjen. Her finner en ofte komplekse og langvarige oppdrag, noe som passer Mikkel godt.

Utenfor jobb bruker Mikkel mye tid på løping. Her gjelder det å bli så rask som mulig på alt fra halvmaraton til ymse motbakkeløp. Det sykles også en del på søndager med fint vær, disse dagene kommer ikke så alt for ofte i Bergen. Om vinteren finner du Mikkel med ski på bena. Det skal skøytes på flatmark, og randonnee i fjellene.

Mikkel fikk øynene opp for Sonat på grunn av det gode sosiale miljøet, størrelsen på bedriften og de interessante kundene.', 'Sviker, Slow Runner', 'Bergen', 'https://cdn.sanity.io/images/pj4buh1l/production/2b83503dc955dcd8d80bad80df8c70c2dc133f38-1200x1804.jpg', '2025-03-06 17:59:43.376648+00');
INSERT INTO employees (name, phone, email, bio, skills, location, image, created_at) VALUES ('Mats Elias Davidsen', '90228200', 'Mats.davidsen@sonat.no', 'Mats er en fullstack utvikler som har erfaring med en rekke teknologier og rammeverk, den siste tiden har fokus vært på .NET og React. Han er utdannet sivilingeniør fra NTNU og på fritiden liker han å være aktiv og følge med på fotball .', 'Fullstack utvikler, .NET, React', 'Oslo', 'https://cdn.sanity.io/images/pj4buh1l/production/1f2865606dba2c810432440e75a86f6c68514949-2072x1540.png', '2025-03-06 17:59:43.376648+00');
INSERT INTO employees (name, phone, email, bio, skills, location, image, created_at) VALUES ('Martin Leithaug', '40201703', 'martin.leithaug@sonat.no', 'Martin er en fleksibel og erfaren fullstack utvikler med en forkjærlighet for frontend. Har har stort spekter i bransjeerfaring fra compliance management og ERP til e-læring og strømmetjenester der han har jobbet mest med React, Angular, C# og Azure.', 'Systemutvikling, web, .net, java og mobil', 'Bergen', 'NULL', '2025-03-06 17:59:43.376648+00');
INSERT INTO employees (name, phone, email, bio, skills, location, image, created_at) VALUES ('Markus Johan Haugsdal', '95817425', 'Markus J. Haugsdal ', 'Markus er en fullstack utvikler med Java som hovedspråk, med bakgrunn i datateknikk fra USN. Han har lang erfaring fra offentlig sektor hvor han har jobbet med samfunnskritiske systemer innenfor e-helse. Der han har jobbet både med utvikling og drift. Markus er en jovial type og humørspreder som alltid er behjelpelig. I tidligere prosjekt har han figurert både som utvikler og DevLead. Av kolleger blir Markus beskrevet som en person med høy kapasitet som elsker å løse problemer.
Fritiden går for det meste bort på serier med kjæresten, dataspill med venner eller fotball. Han er også mer enn gjennomsnittlig interessert i politikk og historie, og store deler av dagen går bort til podcasts og youtube.', 'NULL', 'Oslo', 'https://cdn.sanity.io/images/pj4buh1l/production/f2801c663b6cab6c5673677cfa5e0d59cc63ab86-1491x1156.png', '2025-03-06 17:59:43.376648+00');
INSERT INTO employees (name, phone, email, bio, skills, location, image, created_at) VALUES ('Magnus Ødegård Bergersen', '48090439', 'magnus.bergersen@sonat.no', 'Møt vår 28 år gamle innbygger fra Stavanger! Han har gått gjennom utdanningen ved HVL og UiB i Bergen og har også erfaring innen spillutvikling ved Voss FHS. Han har vært fascinert av teknologi helt siden barndommen, og utforsking av teknologiske løsninger har alltid vært en naturlig del av livet hans. På fritiden liker han å utforske nye ølstiler, fordype seg i spennende spill og nyte eventyrene som snowboardkjøring bringer med seg. Når det kommer til teknologi er han eksperten i Java, og har den ekstra lille interessen for sikkerhet.', 'Java, sikkerhet, Cloud, Internet of Things, webapplikasjoner, køsystemer', 'Oslo', 'https://cdn.sanity.io/images/pj4buh1l/production/bcdbe78af96d7feaec2fcc95350ba17a13a28c14-1080x1444.png', '2025-03-06 17:59:43.376648+00');
INSERT INTO employees (name, phone, email, bio, skills, location, image, created_at) VALUES ('Lauritz Valved', '45699470', 'lauritz.valved@sonat.no', 'Lauritz har over flere år utviklet VR simulatorer og opplevelser til blant annet messebruk, forskning og behandling/rehabilitering. I tillegg har han over 10 års erfaring som generalist innen 3D visualisering for blant annet olje og energi, shipping og fiskerinæringen. 

Med denne kombinasjonen har han kompetansen til å ta "serious games" prosjekter fra konsept til i mål. Han har mastergrad i programutvikling fra Universitetet i Bergen og Høgskulen på Vestlandet. I tillegg har han en Bachelor of Arts i 3D spillgrafikk fra Noroff og University of Teesside. 

På fritiden sitter han gjerne med spill, tegneblokken eller prosjekter innen 3d-printing.', 'Programutvikling, spillutvikling, 3D artist/generalist, Virtuell Virkelighet (VR)', 'Bergen', 'https://cdn.sanity.io/images/pj4buh1l/production/73e9e5cab7df0834066f2296d3c809aee5fd453a-1467x1402.jpg', '2025-03-06 17:59:43.376648+00');
INSERT INTO employees (name, phone, email, bio, skills, location, image, created_at) VALUES ('Lars Aaberg', '45851242', 'lars.aaberg@sonat.no', 'Lars Aaberg er konsulent i Sonat og har vært med siden oppstarten i 2012. Han har de siste årene jobbet som løsningsarkitekt og utvikler for flere av Norges mest innovative bankprosjekter. Han er opptatt av å gjøre komplisert spaghettiarkitektur enkelt, og setter en ære i å designe systemer som er robuste, med god overvåking og lette å vedlikeholde. 

Det var ikke alltid gitt at Lars skulle jobbe med IT, da han er utdannet elektroingeniør. I stedet endte Lars opp med å utvikle hipster bankprosjekter, og har på mystisk vis gjennom karrieren blitt utvikleren i Bergen med flest Github stjerner. 

Lars har valgt sonat fordi de alltid har det gøy på sosiale arrangementer, og fordi de prioriterer faglig utvikling.', 'Systemarkitektur, skyarkitektur og systemutvikling', 'Bergen', 'https://cdn.sanity.io/images/pj4buh1l/production/429ed1cf5dd479837ffb7afd60af51c7734ba800-2200x1467.jpg', '2025-03-06 17:59:43.376648+00');
INSERT INTO employees (name, phone, email, bio, skills, location, image, created_at) VALUES ('Kolbein Foldøy', '48118377', 'kolbein.foldoy@sonat.no', 'Kolbein har en mastergrad i programutivkling fra Universitet i Bergen/Høgskulen på Vestlandet. Han har jobbet som konsulent siden endt utdanning. Han har siden jobbet som .NET-utvikler og løsningsarkitekt for en rekke kunder i offentlig og olje- og gassektoren. På fritiden liker han å holde seg aktiv med styrketrening, gaming, musikk, og følger ivrig med på UFC og Formel 1. Kolbein begynte i Sonat på grunn av fokuset på faglig utvikling, samt ønske om å tilhøre et godt kollegialt miljø.', 'Systemutvikling, backend, API, .NET', 'Bergen', 'https://cdn.sanity.io/images/pj4buh1l/production/8eafdba1c149028869b6fb190c8b51001026188c-3024x4032.jpg', '2025-03-06 17:59:43.376648+00');
INSERT INTO employees (name, phone, email, bio, skills, location, image, created_at) VALUES ('Kjartan Storli', '90207278', 'Kjartan.storli@sonat.no', 'Kjartan er konsernsjef i Sonat og daglig leder i Sonat Consulting Bergen.
Han startet karrieren sin som programmerer, ved siden av informatikk-studiene, hvor han jobbet med programvare for kraftbransjen. Deretter jobbet han som konsulent og utvikler i flere år. Etter hvert dreide karrieren over mot ledelse og rådgiving i både store og små bedrifter. 
De senere årene har hovedinteressen vært hvordan lykkes med å sy sammen teknologi, design og organisasjonskompetanse i en moderne produktorganisasjon. 
Som leder er Kjartan  opptatt er å skape en kultur hvor trygghet, eksperimentering og læring er naturlige elementer i hverdagen. Kombinert med klare mål gir dette det beste grunnlaget for nyskaping og utvikling.
Kjartan har Master in Technology Management på NHH, NTNU og Massachusetts Institute of Technology (MIT), og Master in Computer Science fra UiB.', 'Konsernsjef
Ledelse, strategi, prosessforbedring, forretningsutvikling', 'Bergen', 'https://cdn.sanity.io/images/pj4buh1l/production/43db9515015379166f29f2d461d88f7686a93927-1101x734.jpg', '2025-03-06 17:59:43.376648+00');
INSERT INTO employees (name, phone, email, bio, skills, location, image, created_at) VALUES ('Ketil Ingebrigtsen', '95982911', 'ketil@sonat.no', 'Ketil er selger, nettverksbygger og talentutvikler. Han har mange års erfaring innen forretningsutvikling og rådgivning på tvers av ulike bransjer og sektorer. Ketil jobber tett med kundene for å forstå deres forretningsbehov. Selv om han alltid har vært begeistret for mulighetene teknologi skaper, setter han mennesker aller høyest. Ketil er en stolt innbygger i teknologihovedstaden og har et stort hjerte for oppstartsselskapene i regionen.', 'Sales Management, Advisory, IT Strategy, Human Resources (HR)', 'Trondheim', 'https://cdn.sanity.io/images/pj4buh1l/production/2e25a2ceb88913f7b2b3f38dd1c4f2421842e586-7010x4675.jpg', '2025-03-06 17:59:43.376648+00');
INSERT INTO employees (name, phone, email, bio, skills, location, image, created_at) VALUES ('Jostein Kjerstad', '47848734', 'jostein.kjerstad@sonat.no', 'Jostein har en master i datateknologi fra NTNU og jobber som seniorutvikler hos Sonat. Han har til nå jobbet hovedsakling som .NET og backendutvikler men er ikke fremmed for åta tak i nye teknologier da han ikke er personen til å takke nei til en utfordring.

På fritiden liker han å drive med tauklatring, reise jorden rundt, gå fortest mulig på skøyteski eller å forbedre seg i en av de mange racketsportene som finnes. I tillegg har han en ekstra stor interesse for musikk og er alltid på jakt etter en ny konsert eller festivalopplevelse

Jostein valgte Sonat på grunn av det godt etablerte faglige miljøet hvor han kan vokse videre hos en av de mange spennende kundene.', 'Systemutvikling, Backend, C#/.NET, Azure og skyteknologi, algoritmer og maskinlæring.', 'Bergen', 'https://cdn.sanity.io/images/pj4buh1l/production/0a60334afa2aae7a5f3fc6c5541ae0b53a2ec329-3024x4032.jpg', '2025-03-06 17:59:43.376648+00');
INSERT INTO employees (name, phone, email, bio, skills, location, image, created_at) VALUES ('Jonas Waage', '41680174', 'jonas.waage@sonat.no', 'Jonas Waage har vært seniorkonsulent i Sonat siden 2018. Han har en mastergrad i informatikk fra UiB med spesialisering innenfor visualisering. 

Den trengs når han prøver å se lyset fra unøvendigkompleksitetsdypet. De siste årene har fokus vært utvikling av backend systemer innen bank og finans, telekom og media, hvor han er opptatt av å lage løsninger som er robuste, vedlikeholdbare og så enkle som mulig. 

På fritiden er Jonas først og fremst far, men han liker også å utforske forskjellige teknologier. Interessene spenner bredt, med alt fra spillutvikling sammen med barna til selvpåførte spillteori og optimering-problemer. 

Jonas valgte Sonat fordi Sonat setter felles faglige interesser i fokus gjennom månedlige fagdager.', 'Design og systemutvikling i en Java/JVM basert stack, samt datagrafikk, visualisering og GPU basert prosessering.', 'Bergen', 'https://cdn.sanity.io/images/pj4buh1l/production/338c8edc81170385e2b58ec46c250a7c253c282a-2200x1467.jpg', '2025-03-06 17:59:43.376648+00');
INSERT INTO employees (name, phone, email, bio, skills, location, image, created_at) VALUES ('Jonas Helgemo', '93263025', 'jonas.helgemo@sonat.no', 'Jonas er utdannet Master of Science i Computational Science fra Universitetet i Oslo. I prosjektene har han hatt ansvar for arkitektur og løsningsdesign, utviklingsmiljø, utvikling og leveranser. Han har hatt roller som arkitekt, utvikler og teamleder. Jonas har erfaring med både .NET- og Java/Open Source-plattformen, samt med Azure, AWS og Google Cloud Platform.

Jonas har erfaring med arkitektur for forretningskritiske systemer i bransjer som offentlig, energi, media, telecom, oppdrett m.m.', 'Analyse, arkitektur, prosjektplanlegging,utvikling, IT ledelse.', 'Trondheim', 'https://cdn.sanity.io/images/pj4buh1l/production/afaf82a0e89c82d82a84f41d452412f4be540c09-7612x5077.jpg', '2025-03-06 17:59:43.376648+00');
INSERT INTO employees (name, phone, email, bio, skills, location, image, created_at) VALUES ('Jon Harald Øymyr', '95723475', 'Jon.oymyr@sonat.no', 'Jon liker å lage kule apper, og har jobbet med dette i flere år. 

Han liker å kaste seg over nye ting og har vært innom mye forskjellig teknologi og innen flere bransjer. Jon er opptatt av Android og Google sine løsninger, samt app-tilpassede sky-løsninger som Firebase og AWS. I tillegg er han interessert i og har kunnskap om cross-platform-løsninger som Flutter og React Native. 

På fritiden liker han å drive med kampsport, løpe, bade med sine barn, samt brygge og drikke øl. Han har samboer og to barn på 3 og 6 år som skaper mye frustrasjon, men heldigvis enda mere morro.', 'App-utvikling, front-/backend-utvikling basert på Java/Kotlin, Firebase, AWS og DevOps.', 'Bergen', 'https://cdn.sanity.io/images/pj4buh1l/production/2b518423992f97105fa9b86a1cc56dfe27d2fa73-2200x1467.jpg', '2025-03-06 17:59:43.376648+00');
INSERT INTO employees (name, phone, email, bio, skills, location, image, created_at) VALUES ('Brian Baird', '40636253', 'brian.baird@sonat.no', 'Brian har mer enn 20 års erfaring innen programvareutvikling fra ulike bransjer som energi, helse og offentlig sektor. Her har han jobbet som løsningsarkitekt, systemarkitekt, systemingeniør og fullstack-utvikler ved å bruke ulike teknologier som .Net, React, Azure, K8s, Dapr, og OAuth.

Som person er han positiv, løsningsorientert, jobber strukturer, og har et sterkt fokus på verdiskapning. På fritiden bruker han tiden på å være pappa, snekre, drive med crossfit, fotball og litt gitarspilling.', 'Arkitektur, Azure, Systemutvikling, Sikkerhet', 'Trondheim', 'https://cdn.sanity.io/images/pj4buh1l/production/fb06b2404783f20d72592e77e96ce2ae563f17a9-7686x5126.jpg', '2025-03-06 17:59:43.376648+00');
INSERT INTO employees (name, phone, email, bio, skills, location, image, created_at) VALUES ('John Nordgaard', '91726360', 'john.nordgaard@sonat.no', 'John har over 25 års fartstid som løsningsarkitekt, prosjektleder, konsulent og programmerer. Han tok sin mastergrad i informatikk ved Universitetet i Bergen, og har i årenes løp opparbeidet bred erfaring fra store IT-prosjekter hos selskaper som DNB, Tryg, Evry, Skandiabanken og Nera. Ved siden av utvikling av teknologi brenner han også for kunnskapsformidling. Han har tidligere arbeidet deltid som foreleser og sensor ved Institutt for Informasjonsledelse på BI, og fungert som mentor i opplæring av utviklerteam hos diverse bedrifter. Han var også initiativtaker til oppstarten av JavaBIN i Bergen.', 'Løsningarkitekt, utvikling og prosjektledelse. ', 'Bergen', 'https://cdn.sanity.io/images/pj4buh1l/production/39b6b8a116b476b1a5eb18b42c45e8a60d7b06c7-2650x3400.jpg', '2025-03-06 17:59:43.376648+00');
INSERT INTO employees (name, phone, email, bio, skills, location, image, created_at) VALUES ('Johannes Erdahl Andresen', '99509035', 'johannes.andresen@sonat.no', 'Johannes er en 27 år gammel teknologi-entusiast med en sterk lidenskap for utvikling. Han har en utdannelse som dataingeniør fra OsloMet, og har over 3 års erfaring som fullstack-utvikler. Han har jobbet i bank- og forsikringsbransjen, hvor han har fått god innsikt i å lage brukervennlige og effektive applikasjoner som henger godt sammen.
På fritiden holder Johannes seg aktiv med idretter som golf, fotball og tennis, samtidig som han alltid har et par sideprosjekter på gang for å utforske og lære seg nye teknologier.', 'Fullstack-utvikler', 'Oslo', 'https://cdn.sanity.io/images/pj4buh1l/production/206dbeeac187552d12724a08800f6c227c3d5137-960x511.png', '2025-03-06 17:59:43.376648+00');
INSERT INTO employees (name, phone, email, bio, skills, location, image, created_at) VALUES ('Joakim Hop', '92097579', 'joakim.hop@sonat.no', 'Joakim har lang erfaring som utvikler i innen ulike bransjer blant annet bank, offentlige tjenester og telekommunikasjon. Som utvikler i Sonat får han muligheten til å jobbe med nye utfordringer hver dag og levere spennende produkter til kunder i ulike bransjer. 

Joakim trives godt i det sosiale og faglig sterke miljøet i Sonat.', 'Front-end utvikling og back-end utvikling basert på Java- og Microsoft teknologi og front-end verktøy.', 'Bergen', 'https://cdn.sanity.io/images/pj4buh1l/production/c8e816b21235344c307ebff3f94155dfe8a875fe-2200x1467.jpg', '2025-03-06 17:59:43.376648+00');
INSERT INTO employees (name, phone, email, bio, skills, location, image, created_at) VALUES ('Jarle Børsheim', '97150183', 'Jarle.borsheim@sonat.no', 'Jarle er utvikler, arkitekt og en god potet som ikke er redd for å skitne fingrene til. Han liker å prøve ny ting og har jobbet med mye forskjellig teknologi, innenfor diverse bransjer som bank, media, energi, helse og kommunale tjenester. 

Han liker å være sosial med kollegaer, familie og venner og drar gjerne i gang noe gøy. Bruker mesteparten av tiden i en familie bestående av 1 kone, 2 barn, 1 katt og 3 planter. 

På fritiden bruker han også tid på å spille fotball, buldring med jentene sine, løpe i fjellet og drikke øl mens han taper i fps-spill.', 'Back-end og front-end utvikling basert på Java og .Net og mobile løsninger.
Løsningsarkitektur og prosesser.', 'Bergen', 'https://cdn.sanity.io/images/pj4buh1l/production/8a16ab46b2d1c9c5e6568059d57beb674e774bc8-1467x1695.jpg', '2025-03-06 17:59:43.376648+00');
INSERT INTO employees (name, phone, email, bio, skills, location, image, created_at) VALUES ('Jannicke Nielsen', '45395866', 'jannicke.nielsen@sonat.no', 'Jannicke har en bachelor i informatikk fra NTNU. Hun har erfaring og kompetanse innen design og utvikling av IT-systemer innen bank, helse og kontraktshåndtering. 

Jannicke er brukerorientert og søker å finne gode universelle løsninger som frontendutvikler.', 'Systemutvikling frontend og backend.', 'Bergen', 'https://cdn.sanity.io/images/pj4buh1l/production/deacd99db366318709782d72fa24942a78a39808-2200x1467.jpg', '2025-03-06 17:59:43.376648+00');
INSERT INTO employees (name, phone, email, bio, skills, location, image, created_at) VALUES ('Jan-Terje Sørensen', '92289894', 'jan-terje.sorensen@sonat.no', 'Jan-Terje er en engasjert tastaturtrykker med over 10 år erfaring som konsulent innen utvikling av IT prosjekter. Han har jobbet med alt fra forvaltning til implementasjon av nye produkter og innføring av ny teknologi. Jan-Terje har, blant andre, vært med å utvikle 
- Egen pensjonskonto for DNB Liv 
- Nettbanken til Sparebanken Vest 
- Låneprodukter Buffer for Sparebanken Vest 
- Partitest og nyhetsstips for TV2 
- Mediaarkiv for Nasjonalbiblioteket 

I Sonat er han partner og fullstack-utvikler, i tillegg til å ha ansvar som prestasjonsutvikler for en gruppe kollegaer. Tilbakemeldinger vi har fått av våre kunder er at han raskt setter seg inn i problemstillinger, er engasjert og bidrar til å skape et godt miljø rundt seg. 

Jan-Terje valgte Sonat for å kunne jobbe under de beste betingelsene, i det beste IT-miljøet i Bergen.', 'Design og systemutvikling innen Java og C#, Azure, Teknisk arkitektur, Android, JavaScript.', 'Bergen', 'https://cdn.sanity.io/images/pj4buh1l/production/ba4b9138315b3196ddfcbca835897833dc3558a2-1467x1499.jpg', '2025-03-06 17:59:43.376648+00');
INSERT INTO employees (name, phone, email, bio, skills, location, image, created_at) VALUES ('Ingrid-Alice Bløtekjær', '45505548', 'ingrid-alice.blotekjar@sonat.no', 'Ingrid-Alice startet i Sonat Oslo i januar 2024. Hun har en bachelorgrad i web- og mobilutvikling fra Høyskolen Kristiania, og har jobbet mest med mobile løsninger siden 2021. Hennes fokusteknologier er Flutter, Kotlin og Javascript/TypeScript, grensesnittdesign og brukervennlighet, og hun liker spesielt godt mobile flater. Ingrid-Alice trives godt når hun jobber i team, og for henne er det viktig å løse problemer, heve egen kompetanse, men også å spille andre gode.
På fritiden foretrekker Ingrid-Alice å løpe, trene styrke eller gå på langrenn, og bruker også mye tid på mann og barn. Å lage og spise god mat med venner og familie er heller ikke å forakte!
Ingrid-Alice har valgt Sonat på grunn av det robuste fagmiljøet og muligheten til å heve egen kompetanse.', 'Systemutvikling, mobile løsninger', 'Oslo', 'https://cdn.sanity.io/images/pj4buh1l/production/bff51ef46020885defbd95ceb30e07316bdda363-1072x1450.png', '2025-03-06 17:59:43.376648+00');
INSERT INTO employees (name, phone, email, bio, skills, location, image, created_at) VALUES ('Ingebrigt Winjum', '40863512', 'ingebrigt.winjum@sonat.no', 'Ingebrigt har jobbet som seniorkonsulent i Sonat siden 2019. Han har lang erfaring med utvikling av backend for webbaserte løsninger, og trives best i krysset mellom forretningsbehov og teknologi. Kjernekompetansen er utvikling på .NET-plattformen, samt regelmotorutvikling. 

Han har også erfaring med skytjenester, devops, smidige metoder og automatisert testing. Ingebrigt er utdannet sivilingeniør i teknisk fysikk ved NTNU. 

På fritiden liker Ingebrigt å gå tur på byfjellene, se på fotball, og gå på pubquiz med venner. 

Ingebrigt valgte Sonat fordi han kjente noen dyktige og hyggelige folk som jobbet her fra før, som kunne fortelle om et veldig godt miljø, både faglig og sosialt.', 'Systemutvikling, MS.Net', 'Bergen', 'https://cdn.sanity.io/images/pj4buh1l/production/2f9576c8f48ec3e8c6ea662b19e0b8a3f36fcf3e-1467x1560.jpg', '2025-03-06 17:59:43.376648+00');
INSERT INTO employees (name, phone, email, bio, skills, location, image, created_at) VALUES ('Herman Willem Haukenes', '46784120', 'herman.haukenes@sonat.no', 'Herman har erfaring innen management consulting og har en sterk interesse for teknologi og koding. Han trives i skjæringspunktet mellom teknologi og forretning, og er en relasjonsbygger som er både vennlig og imøtekommende. Han er ivrig etter å lære mer om Python og fordype seg i data engineering, samtidig som han ivaretar det forretningsmessige aspektet.Herman er klar til å ta på seg roller som både prosjektleder eller prosjektstøtte. Han setter stor pris på samarbeid og er ikke redd for å ta på seg nye utfordringer.', 'Prosjektledelse, Forretningsutvikling, Innsiktsarbeid/Data, Strategi, Analyse, Python', 'Oslo', 'https://cdn.sanity.io/images/pj4buh1l/production/ca8626ce763920fd38f8c417ce9a17f88f69232a-4032x3024.jpg', '2025-03-06 17:59:43.376648+00');
INSERT INTO employees (name, phone, email, bio, skills, location, image, created_at) VALUES ('Herman Ferre', '90124113', 'herman.ferre@sonat.no', 'Herman er seniorkonsulent i Sonat. Han har vært .NET-utvikler siden han tok fatt på arbeidslivet i 2018, og har gjennom ulike prosjekter opparbeidet seg full stack-kompetanse. Han har en master fra studieprogrammet Ingeniørvitenskap & IKT ved NTNU i Trondheim, inkludert et utenlandsopphold ved University of California, Santa Barbara.Herman er nysgjerrig, og opptatt av å levere kvalitet. Han liker å innta en aktiv rolle i prosjekter, og bidrar gjerne med forslag og input til løsninger overfor kunden. Han stortrives derfor i team, da han mener at alle har noe å bidra med og at man sammen kommer frem til den beste løsningen, i tillegg til at det gir et læringsutbytte for alle.Som person er Herman positiv, ydmyk og sosial. Han liker mennesker og er glad i å bygge nye relasjoner, både sosialt og profesjonelt. Ellers setter han pris på litt fart og spenning, og er glad i raske biler.', 'Frontend: React.js, TypeScript, HTML5, CSS3, JavaScript
Backend: Microsoft .NET, C#, Entity Framework, SQL Server, PostgreSQL', 'Oslo', 'https://cdn.sanity.io/images/pj4buh1l/production/35c24474afb2eec36d8593842d9b991734212c5b-2403x3600.jpg', '2025-03-06 17:59:43.376648+00');
INSERT INTO employees (name, phone, email, bio, skills, location, image, created_at) VALUES ('Henrik Nyhus', '90780670', 'henrik.nyhus@sonat.no', 'Henrik jobber som senior data scientist i Sonat med bakgrunn i statistikk fra LMU München og UiO. 

Han har en sterk kompetanse innen multivariat statistisk dataanalyse, data wrangling, visualisering og romlig statistikk. 

Henrik har over seks års erfaring fra transport, retail, maritime samt og olje- og energibransjen med ekspertise i tilstandsovervåking. Han jobber med systemarkitektur, skalerbare maskinlæringsplattformer og automatiserte rapporteringssystemer. Henrik er opptatt av integritet, struktur og flyt av data, hvor enkle løsninger fremfor lettvinte er hans mantra. Han har to store verktøykasser: R og Python. 

Work hard, play hard. Når Henrik ikke er på jobb er han stort sett å finne i et telt på Vikafjellet. Topptur, speed- og paragliding, packrafting og seiling er stikkord. 

Henrik valgte Sonat for bli en del av vestlandets sterkeste data science-miljø hvor han kan jobbe på spennende prosjekter.', 'Statistisk dataanalyse og maskinlæring', 'Bergen', 'https://cdn.sanity.io/images/pj4buh1l/production/f70e040154335b48a03a61bcc5e9efd3db62bdf5-2200x1467.jpg', '2025-03-06 17:59:43.376648+00');
INSERT INTO employees (name, phone, email, bio, skills, location, image, created_at) VALUES ('Helge Skjellevik', '97479234', 'helge.skjellevik@sonat.no', 'Helge har erfaring med arkitektur, design og systemutvikling fra banksektor. Han har arbeidet med utvikling av regnskaps-, forsikrings- og andre driftskritiske løsninger. Kjernekompetansen hans ligger på web- og applikasjonsutvikling.', 'Arkitektur, systemintegrasjon og systemutvikling på java og mobile plattformer.', 'Bergen', 'https://cdn.sanity.io/images/pj4buh1l/production/d89d9a395eb834d8f740f9e463b5467d18dfeca3-2200x1467.jpg', '2025-03-06 17:59:43.376648+00');
INSERT INTO employees (name, phone, email, bio, skills, location, image, created_at) VALUES ('Hakon Ingvaldsen', '95224607', 'hakon.ingvaldsen@sonat.no', 'Håkon har mer enn 23 års erfaring som systemutvikler, og har i brorparten av sin karriere jobbet med store komplekse løsninger innenfor mange bransjer i det offentlige og det private næringsliv.
Det har blitt mye både java og .NET, mest backend men også frontend, mye sky, DevOps og API utvikling de senere år.
Håkon har mang en gang spurt seg selv om det ikke snart er på tide å "ta steget videre" og bli prosjektleder eller noe sånt, men havner stadig tilbake med nesen inni koden.
Dette fordi det er alt for kjekt å programmere, skape noe, løse problemer og få ting til å virke. Koden lokker og fingrene begynner å klø!
En skomaker som blir ved sin lest altså.
Håkon er en fleksibel konsulent som kjenner godt alle deler av systemutviklingsprosessen, samarbeider godt og blir gjerne en ressursperson i teamene han havner i.
På privaten har han to døtre på 10 og 12 år som han har annenhver uke. Hver sommer er det 10+ dager på fjellet med telt og fiskestang og hver onsdag er det bedriftsorienteringsløp. Akkurat som med programmeringen nekter han å gi seg med å spille i band, selv om 20 årene er vel passert.
Håkon valgte Sonat fordi han allerede kjenner en haug med Sonatere og vet at Sonat har de beste folkene. Sonat har perfekt balanse mellom samhold og individuell tilpasning og har rettferdige og gode betingelser.', 'Java og .NET, mest backend men også frontend, sky, DevOps og API', 'Bergen', 'https://cdn.sanity.io/images/pj4buh1l/production/d6ee49c4996fe37eafa496744c97af1b2ba467fc-1677x2000.jpg', '2025-03-06 17:59:43.376648+00');
INSERT INTO employees (name, phone, email, bio, skills, location, image, created_at) VALUES ('Fredrik Smaamo', '93422099', 'fredrik.smaamo@sonat.no', 'Fredrik Smaamo har vært partner og seniorkonsulent i Sonat siden 2019. Han vil helst jobbe med hele stacken, og trives med både utforming av arkitektur og implementering av løsninger. Han er fan av continuous deployment og syntes at infrastruktur ser best ut som kode. 

Han har et bankende hjerte for andre utviklere som skal kna videre på koden han har skrevet, og fokuserer alltid på ren og pen kode som skal være lett å forstå. Heller et par kodelinjer ekstra enn en overkomplisert LINQ query som ingen forstår. Dette fører ofte til bedre kode totalt sett. 

Fredrik er svært musikkinteressert og han er en ivrig motorsyklist som gjerne nyter en kjøretur når været tillater dette. 

Han jobber i Sonat fordi han tenker det er lurt å omgi seg med personer som er smartere enn han selv.', 'Systemutvikling, integrasjon, .NET, DevOps, JavaScript og frontend rammeverk', 'Bergen', 'https://cdn.sanity.io/images/pj4buh1l/production/c0604dc09d7d6fc4660c736b0e6672d542e67a1b-2200x1467.jpg', '2025-03-06 17:59:43.376648+00');
INSERT INTO employees (name, phone, email, bio, skills, location, image, created_at) VALUES ('Fredrik Haarde', '45223122', 'fredrik.haarde@sonat.no', 'Fredrik har opparbeidet seg god kunnskap i flere språk og teknologier, spesielt i C# og .NET, Python gjennom Databricks, Java fra studiet, og Terraform for kildekontroll av Azure-ressurser. På fritiden utforsker han front-end rammeverk som React, React Native, Angular og Node, men dykker også inn i nye språk som Swift og Rust. Fredrik har en brennende interesse for koding, og trives best når han blir presentert med utfordringer som byr på læring og driver han til å bli en bedre utvikler. ', 'Dataplattform, utvikling', 'Bergen', 'https://cdn.sanity.io/images/pj4buh1l/production/8dfe191fdb45822723fbc50f0aa11166c7d37527-2317x3161.jpg', '2025-03-06 17:59:43.376648+00');
INSERT INTO employees (name, phone, email, bio, skills, location, image, created_at) VALUES ('Fehmmi Aliti', '46534792', 'fehmmi.aliti@sonat.no', 'Snowflake, Datavarehus, ETL/ELT, Data modellering, Power BI', 'Fehmmi er en data engineer med erfaring i Snowflake, hvor han har jobbet med å utvikle datavarehus som oppfyller forretningsbehov. I det siste har han fokusert på Media Mix Modeling (MMM), og hjulpet kunde med å optimalisere medieforbruket sitt gjennom datadrevne innsikter.
På fritiden liker Fehmmi å være aktiv, spille fotball, og jobbe med sideprosjekter for å utforske nye teknologier.', 'Oslo', 'https://cdn.sanity.io/images/pj4buh1l/production/86c9e4df6fcd8fc0f514e8309911f19897ce7667-2460x2029.jpg', '2025-03-06 17:59:43.376648+00');
INSERT INTO employees (name, phone, email, bio, skills, location, image, created_at) VALUES ('Bentein Thomassen', '95008504', 'bentein.thomassen@sonat.no', 'Bentein er konsulent i Sonat Bergen.
Han begynte sin kodereise med actionscript på ungdomsskolen. Derfra utviklet teknologiinteressen seg trutt til endt bachelor fra dataingeniørlinjen på HVL. Derfra gikk veien innom DNB og Amazon, hvor han jobbet med henholdsvis finans og innholdsmoderering i AWS.
Bentein søker alltid etter nye utfordringer. På fritiden bruker han tid på gaming, skjønnlitteratur, vanlig tur, og koding. Konsulenter fra Sonat gjorde godt inntrykk på Bentein da han jobbet i DNB, og ønsket om å bli del av teamet var sterkt da han returnerte fra sitt arbeidsopphold i Tyskland.', 'Backend i Java, Cloud, CI/CD', 'Bergen', 'https://cdn.sanity.io/images/pj4buh1l/production/4d762193f2b46852d7b508d3b5babdcd0408befb-1200x1413.jpg', '2025-03-06 17:59:43.376648+00');
INSERT INTO employees (name, phone, email, bio, skills, location, image, created_at) VALUES ('Espen Kvalheim', '98608322', 'espen.kvalheim@sonat.no', 'Espen har vært med omtrent fra starten av Sonat sitt eventyr. Han trives med å involvere seg i sin arbeidsplass, og har i dag rollen som gruppeleder for backend fagområdet og er aktiv i sosialkomiteen i Sonat. 

Fra sitt konsulentliv har han lang erfaring fra prosessutvikling, teamledelse og systemutvikling. Espen er en allsidig utvikler som liker å jobbe med hele stacken, og ekstra fornøyd blir han når han får jobbe med noe av det nye som beveger seg innen skyteknologi. 

På fritiden har Espen en tendens til å bli revet med på det meste som innebærer fysisk aktivitet, og det går i sykling, klatring, rulleski, nedoverski, bortoverski, fotball, m.m. 

Espen jobber i Sonat fordi det er en arbeidsplass som legger til rette for at han hele tiden kan utvikle seg, og her har han kolleger han alltid gleder seg til å treffe i sosiale tilstelninger.', 'Teamledelse, systemutvikling og prosessautomatisering.', 'Bergen', 'https://cdn.sanity.io/images/pj4buh1l/production/383dfa6a3f48c90c4bdf2aff9fcaccf877361605-1467x1387.jpg', '2025-03-06 17:59:43.376648+00');
INSERT INTO employees (name, phone, email, bio, skills, location, image, created_at) VALUES ('Erik Bøtun', '94437430', 'erik.botun@sonat.no', 'Erik jobber som senior konsulent, og har fått tittelen sivilingeniør i data fra UiA fra Agder og QUT i Australia, med spesialisering innen kunstig intelligens.
Erik engasjerer seg stort når det gjelder å finne løsninger til framdrift i prosjekter. Han er flink til å se sammenhenger, strukturere arbeidet, og bruke ulike teknologier til å løse enhver utfordring. Teknologier som er i fokus er Microsoft stacken (.Net, C# og Azure), Angular, React, og Machine Learning (Keras, Tensorflow) i Python.
På fritiden prøver han å utvide horisonten sin på områder som frontend, backend, mobile development, machine learning og game development. Dette blir da brukt sammen med hans private DevOps oppsett som består av docker og k8s clusters på hans Raspberry PI 4. Det blir også mye familietid, og en del styrketrening når miniSats er åpent.', '.Net, Python, Angular, React, DevOps og Azure', 'Bergen', 'https://cdn.sanity.io/images/pj4buh1l/production/f9e32fa9f996cee85f679caa6563389840b8dc6d-1200x2032.jpg', '2025-03-06 17:59:43.376648+00');
INSERT INTO employees (name, phone, email, bio, skills, location, image, created_at) VALUES ('Dag Østgulen Heradstveit', '90963610', 'dag.heradstveit@sonat.no', 'Dag har jobbet som seniorkonsulent i Sonat siden 2017 og har en master i Informasjonsvitenskap i fra UiB. 

Han har erfaring i fra forskningsdata, media, finans, kraft, telekom og skytjenester. Han trives best i rollen som utvikler og en lett arkitekt, men trår mer enn gjerne til dersom det er behov på DevOps-siden. Miljø og bærekraft er viktig for Dag. Derfor er han opptatt av ressursbruk i valg av teknologi legges til grunne når valg fattes og mener alle må være sitt ansvar bevisst her. 

På fritiden er det familien, styrketrening, nye programmeringsspråk, små prosjekter for å lære seg ny teknologi og gaming som står i fokus. Det har også blitt tid til å bygge k8s cluster på Raspberry Pi’s for å kjøre småprosjekter. Ansatte i Sonat har et meget godt rykte, både faglig og personlig. Derfor valgte Dag Sonat.', 'Backend basert på Java og Spring teknologier. Frontend basert på funksjonelle språk. Last-testing og DevOps.', 'Bergen', 'https://cdn.sanity.io/images/pj4buh1l/production/3348cd5b37515d764e34017f8236b269efb504e8-1467x1726.jpg', '2025-03-06 17:59:43.376648+00');
INSERT INTO employees (name, phone, email, bio, skills, location, image, created_at) VALUES ('Dag Inge Helgøy', '93014639', 'dag.helgoy@sonat.no', 'Dag Inge har jobbet som konsulent i Sonat siden 2019. Han trives godt som konsulent og har erfaring fra bransjer som eiendom, bank og kollektivtrafikk. 

Dag Inge er utdannet sivilingeniør fra NTNU med en mastergrad i datateknologi. Noe av det beste han vet er å sette seg inn i nye spennende teknologier og problemstillinger, spesielt innen kunstig intelligens. På fritiden finner du enten Dag Inge i fult regntøy i sandkassen eller på sykkeltur med toåringen og kona. Hvis anledningen for barnefri derimot skulle by seg sier han heller ikke nei takk til litt gaming eller en god brettspillkveld. 

Han synes oppdragene i Sonat byr på spennende utfordringer og mulighet for videre læring og utvikling i fagfeltet. Dette, i tillegg til gode månedlige fagdager, var avgjørende i valget om å jobbe for Sonat.', 'Dataanalyse, datalagring, visualisering og maskinlæring', 'Bergen', 'https://cdn.sanity.io/images/pj4buh1l/production/893326ecfec92fde63196b5aa1f5d101ad944539-2200x1467.jpg', '2025-03-06 17:59:43.376648+00');
INSERT INTO employees (name, phone, email, bio, skills, location, image, created_at) VALUES ('Christian Sloper', '90742410', 'christian.sloper@sonat.no', 'Christian Sloper er partner og gruppeleder for data science og maskinlæring i Sonat. Har er over gjennomsnittet opptatt av godt fagmiljø og trivsel, som gjør at han har hatt flere roller i Sonat, deriblant ansatte representant i styret vårt og som gruppeleder. Han mener økt trivsel gir økt effektivitet. 

Christians fokus er på arkitektur og operalisering av datavitenskap, for det er ikke nok å ha datavitenskapsmodellene, de må også tas i bruk. Christian har doktorgrad i algoritmer og kompleksitetsteori, og 15 års erfaring innen datalagring, datateknikk og programmering. På fritiden trives han best i rollen som pappa, og å leke med tallteori og mennesker. 

Christian valgte Sonat fordi han ønsket et seniorselskap med fokus på faglig utvikling og trivsel.', 'Maskinlæring, kunstig intelligense og datamining.', 'Bergen', 'https://cdn.sanity.io/images/pj4buh1l/production/97b2c83193163b3fe9f136329c434e9dfc002d17-2200x1467.jpg', '2025-03-06 17:59:43.376648+00');
INSERT INTO employees (name, phone, email, bio, skills, location, image, created_at) VALUES ('Celina Rongved', '94806269', 'celina.rongved@sonat.no', 'Master of Science student innen Strategisk markedsføringsledelse, med en fullført bachelorgrad i International Management fra New York City. Celina arbeider for øyeblikket som markedsføringskonsulent og fokuserer på å styrke synligheten til Sonat gjennom sosiale medier. Med et solid fundament i markedsføring og en lidenskap for strategi og utvikling, søker Celina kontinuerlig nye muligheter for å utvide sin kompetanse og bidra til suksessen til selskapet.', 'Strategisk markedsføringsledelse, digital markedsføring i sosiale medier. ', 'Oslo', 'https://cdn.sanity.io/images/pj4buh1l/production/33c31f22afcb58d56b3bf01cbc36f5b173b0554f-1670x2014.jpg', '2025-03-06 17:59:43.376648+00');
INSERT INTO employees (name, phone, email, bio, skills, location, image, created_at) VALUES ('Carl-Trygve Melgaard', '41129520', 'Carl.melgaard@sonat.no', 'Carl-Trygve er en engasjert utvikler med flere års erfaring innen finans og forsikring. Han setter pris på en god utfordring, og er aldri fremmed for å utvikle sin kompetanse og lære seg nye ting.
Backend, API og database syns han er aller mest spennende for tiden, men han er absolutt ikke fremmed for å jobbe med web- og app-utvikling.
På fritiden er han glad i sosialisering med familie, kolleger og venner, trening (gymmen, racket-sport, buldring for det meste), Netflix (og lignende), gaming (for det meste fps) og å nyte en reise eller opplevelse i ny og ne.
Carl-Trygve har jobbet med flere dyktige folk fra Sonat tidligere, og da han ønsket seg inn i et sterkt fagmiljø med hyggelige mennesker var Sonat et opplagt valg.', 'Systemutvikling, API, Java/Spring, relasjonsdatabaser', 'Bergen', 'https://cdn.sanity.io/images/pj4buh1l/production/671b964f295bf6b690a474f2fa7b1d499b7c5762-1872x2186.jpg', '2025-03-06 17:59:43.376648+00');
INSERT INTO employees (name, phone, email, bio, skills, location, image, created_at) VALUES ('Børge Haugsdal', '90965253', 'borge.haugsdal@sonat.no', 'Børge har en allsidig bakgrunn og mer enn 20 års erfaring som systemutvikler. Børge har de senere årene opparbeidet seg en unik kompetanse innen automatisering, kontinuerlig utvikling, kontinuerlig integrasjon, deploy og automatisert testing.

Børge har jobbet med Java relaterte løsninger med hovedvekt på Open Source, tjenesteorientert arkitektur og microservices.', 'Arkitektur, systemintegrasjon og systemutvikling med JAVA som hovedspråk.', 'Oslo', 'https://cdn.sanity.io/images/pj4buh1l/production/a021e80eb95886e3561229ffd3db7aaa26db4085-1632x1102.png', '2025-03-06 17:59:43.376648+00');
