export enum Partner {
  Trumf = "NorgesGruppen",
  Unknown = "Unknown",
}

export enum TravelPartner {
  Flytoget = "Flytoget | Points Earned",
  TaxiFix = "Taxifix",
  OsloTaxi = "Oslo Taxi",
  TromsoTaxi = "Tromsø Taxi",
  NorlandTaxi = "Nordland Taxi",
  Norgesbuss = "Norgesbuss",
  StavangerTaxi = "Stavanger Taxi",
  TaxiSentralen = "Taxisentralen",
  VestfoldTaxi = "Vestfold Taxisentral",
  MoreTaxi = "Møre og Romsdal Taxi",
}

export enum ScandinavianAirlinesPartner {
  Flights = "SAS Flights",
  BioFuel = "SAS BioFuel",
  PointPurchase = "SAS Point Purchase",
  ConsciousTraveler = "SAS Conscious Traveler",
  Claim = "SAS Claims",
  PointTransfers = "Point Transfers",
  Intro = "EuroBonus Intro",
  MillionaireCampaign = "Millionaire Campaign",
}

export enum HotelPartner {
  EuroBonusHotels = "EuroBonus-Hotel stay | Points Earned",
  Radisson = "Radisson Hotels",
  Scandic = "Scandic Hotels | Points Earned",
  SmartHotel = "SmartHotel",
  FrognerHouse = "Frogner House",
  BankenHotel = "Banken Hotel",
  SanktJorgen = "Sankt Jörgen",
  ThonHotels = "Thon Hotels",
  Hilton = "Hilton Hotels",
}

export enum CreditCardPartner {
  Amex = "Amex Norway Reward | Points Earned",
  Dnb = "DNB Rewards | Points Earned",
  Lunar = "Lunar NO | Points Earned",
  SasMC = "MasterCard Reward Norway | Points Earned",
  TravelWallet = "Travel Wallet | Points Earned",
  WideroeKortet = "Widerøe-kortet | Points Earned",
  DinersClub = "Diners Club",
}

export enum HomePartner {
  Fjordkraft = "Fjordkraft | Points Earned",
  Verisure = "Verisure Norge | Points Earned",
  Aftenposten = "Aftenposten",
  DagensNæringsliv = "Dagens Näringsliv | Points Earned",
  LiveNation = "LiveNation | Points Earned",
  NordiskVentilasjonsrens = "Nordisk Ventilasjonsrens",
  TideForsikring = "Tide Forsikring",
}

export enum RentalCarPartner {
  Avis = "Avis",
  Hertz = "Hertz",
  Sixt = "SIXT",
}

export enum EuroBonusShopPartner {
  EuroBonusShop = "Shop",
  Nikita = "Nikita",
  Rituals = "Rituals",
  Morris = "Morris",
  Samsung = "Samsung",
  OneCall = "OneCall",
  Interflora = "Interflora",
  RoyalCaribbeanCruises = "Royal Caribbean Cruises",
  CBDNordic = "Cbd Nordic",
  EleniChris = "Eleni & Chris",
  Chillout = "Chillout",
  Lildog = "Lildog",
  Golfamore = "Golfamore",
  NorFloor = "Norfloor",
  Hultens = "Hultens",
  FarSunSolskjerming = "Far&Sun Solskjerming",
  ByBenson = "By Benson",
  MyScreens = "My Screens",
  HurtigrutaCarglass = "Hurtigruta Carglass",
  DitecBilpleie = "Ditec Bilplpeie",
  VonDoren = "Von Doren",
  Mulberry = "Mulberry",
  HellyHansen = "Helly Hansen",
  QOMO = "Qomo",
  MilesPerHour = "Miles Per Hour",
  TailorStore = "Tailor Store",
  LuxReaders = "LuxReaders",
  ACPerchs = "A.C. Perchs",
  CruiseAway = "CruiseAway",
  Solentro = "Solentro",
  LifeJourney = "Life Journal",
  Tivoli = "Tivoli",
  CodanForsikring = "Codan Forsikring",
  SteenStrom = "Steen & Stroem",
  FangenePaaFortet = "Fangene på Fortet",
  BjornBorg = "Björn Borg",
}

export enum RestaurantPartner {
  DognVill = "Døgnvill",
  Egon = "Egon",
  Wolt = "Wolt",
  Sumo = "Sumo",
  CafeMunk = "Cafe Munk",
  TrattoriaSud = "Trattoria Sud",
  ECDahls = "E.C. Dahls",
  MissGin = "Miss Gin",
  Brasilia = "Brasilia",
  Escalon = "Escalon",
  FishCow = "Fish&Cow",
  Spiseriet = "Spiseriet",
  Eldhuset = "Eldhuset",
  Fisketorget = "Fisketorget",
  JohnnyRockets = "Johnny Rockets",
  HjemmeHosSvigers = "Hjemme Hos Svigers",
  Feinschmecker = "Feinschmecker",
  BolgenMoi = "Bølgen & Moi",
  RorBua = "Rorbua",
  Casbar = "Casbar",
  Vulkanfisk = "Vulkanfisk",
  Fiskeriet = "Fiskeriet",
  Wallmans = "Wallmans",
  KafeAsylet = "Kafe Asylet",
  OnkelOskar = "Onkel Oskar",
  NydalenBryggeri = "Nydalen Bryggeri & Spiseri",
  VillaParadiso = "Villa Paradiso",
  Amass = "Amass",
  DistrictTonkin = "District Tonkin",
  Farang = "Farang",
  StockholmFisk = "Stockholm Fisk",
  Klosteret = "Klosteret",
  Boqueria = "Boqueria",
  Stortorgskalleren = "Stortorgskällaren",
  CafeSorgenfri = "Cafe Sorgenfri",
  EntrecoteByTrancher = "Entrecote by Trancher",
  NyhavnsFergekro = "Nyhavns Færgekro",
  AmundsenBrygger = "Amundsen Bryggeri & Spiseri",
  EducationNationale = "L'education Nationale",
  Cartels = "Latin American Kitchen & Bar",
  Fratelli = "Fratelli",
  CafeTrold = "Cafe Trold",
  LundbergsVaskor = "Lundbergs Väskor",
  ChinaPalace = "China Palace",
  Zalt = "Zalt",
  Palegade = "Palægade",
  Magasasa = "Magasasa Dim Sum",
}

export enum AirlinePartner {
  OS = "Austrian Airlines",
  BN = "Brussels Airlines",
  AC = "Air Canada",
  CA = "Air China",
  ZH = "Shenzhen Airlines",
  AV = "Avianca",
  OU = "Croatia Airlines",
  MS = "Egyptair",
  ET = "Ethiopian Airlines",
  LH = "Lufthansa",
  A3 = "Aegean Airlines",
  AI = "Air India",
  NH = "All Nippon Airways",
  NZ = "Air New Zealand",
  CM = "Copa Airlines",
  LO = "LOT Polish Airlines",
  TP = "TAP Air Portugal",
  SQ = "Singapore Airlines",
  SA = "South African Airways",
  OZ = "Asiana Airlines",
  LX = "Swiss",
  BR = "EVA Air",
  TG = "Thai Airways International",
  TK = "Turkish Airlines",
  UA = "United Airlines",
  WF = "Widerøe",
  KL = "KLM",
  AF = "Air France",
  VN = "Vietnam Airlines",
  AZ = "Alitalia",
  AM = "Aeromexico",
  AR = "Aerolineas Argentinas",
  CI = "China Airlines",
  MU = "China Eastern Airlines",
  CZ = "China Southern Airlines",
  DL = "Delta Air Lines",
  GA = "Garuda Indonesia",
  KE = "Korean Air",
  ME = "Middle East Airlines",
  RO = "TAROM",
  SU = "Aeroflot",
  SV = "Saudia",
  UX = "Air Europa",
  MF = "XiamenAir",
  SN = "Brussels Airlines",
}
